#!/bin/bash

set -e

which pep8 >/dev/null
which pyflakes >/dev/null

(
    cd $(git rev-parse --show-toplevel)
    pep8 src setup.py
    pyflakes src setup.py
    doc8 docs
    python setup.py check -r
)

exit 0
