#!/bin/bash

which pep8 >/dev/null || exit $?
which pyflakes >/dev/null || exit $?

(
cd $(git rev-parse --show-toplevel)
pep8 src setup.py || exit $?
pyflakes src setup.py || exit $?
python setup.py check -r || exit $?
)

exit 0
