#!/bin/bash

which pep8 || exit 1

cd $(git rev-parse --show-toplevel)
find src -name '*.pyc' -delete
for py in $(find src -name '*.py'); do
  pep8 "$py" || exit 1
done
python setup.py check -r || exit 1

exit 0